package com.challenge.api.controller;

import com.challenge.api.model.Employee;
import com.challenge.api.model.EmployeeImplementation;
import com.challenge.api.service.EmployeeServiceLayer;
import java.util.List;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Fill in the missing aspects of this Spring Web REST Controller. Don't forget to add a Service layer.
 */
@RestController
@RequestMapping("/api/v1/employee")
public class EmployeeController {

    private final EmployeeServiceLayer employeeServiceLayer;

    public EmployeeController(EmployeeServiceLayer employeeServiceLayer) {
        this.employeeServiceLayer = employeeServiceLayer;
    }

    /**
     * @implNote Need not be concerned with an actual persistence layer. Generate mock Employee models as necessary.
     * @return One or more Employees.
     */

    // Retrieves all Employees. If no Employees exist, return an empty list.
    @GetMapping
    public List<Employee> getAllEmployees() {
        return employeeServiceLayer.getAllEmployees();
    }

    /**
     * @implNote Need not be concerned with an actual persistence layer. Generate mock Employee model as necessary.
     * @param uuid Employee UUID
     * @return Requested Employee if exists
     */

    // Retrieves an Employee by their UUID. If no Employee exists with the provided UUID, return a 404 Not Found status code.
    @GetMapping("/{uuid}")
    public Employee getEmployeeByUuid(@PathVariable UUID uuid) {
        return employeeServiceLayer.getEmployeeByUuid(uuid);
    }

    /**
     * @implNote Need not be concerned with an actual persistence layer.
     * @param requestBody hint!
     * @return Newly created Employee
     */

    // Creates a new Employee. The request body should have all necessary information to create an Employee, except for the UUID, which should be generated by the Service layer.
    @PostMapping
    public Employee createEmployee(@RequestBody EmployeeImplementation requestBody) {
        return employeeServiceLayer.createEmployee(requestBody);
    }
}
